apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redisapi
  name: redisapi
  namespace: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redisapi
  template:
    metadata:
      labels:
        app: redisapi
    spec:
      containers:
      - image: ghcr.io/oaviles/redisapi:7069
        name: redisapi
        env:
        - name: REDIS_CS
          value: < Your Azure Redis Connection String >
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: < Your InstrumentationKey >
        imagePullPolicy: Always
        ports:
        - containerPort: 7069
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "1024m"
---
apiVersion: v1
kind: Service
metadata:
    name: redisapi
    namespace: redis
    labels:
        app: redisapi
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 7069
      protocol: TCP
      name: http
    selector:
        app: redisapi
